"""Load bounding-box reference data into os.bounding_boxes.

Reads bbox_lookup.sqlite (generated by the bbox_lookup Dagster asset) and
inserts rows for geographic areas that appear in our provider data, plus all
district, LA, and county bboxes (small enough to load fully).

Also builds os.la_name_lookup — a mapping from Ofsted local_authority names
to (geo_type, geo_code) so that REDACTED providers can be placed in at least
an LA or county bounding box.

The os.bounding_boxes table is joinable from os.la_places / os.ofsted_places
via (bbox_geo_type, bbox_geo_code).
"""

import os
import sqlite3
from pathlib import Path

from dagster import asset, AssetExecutionContext, MetadataValue

from bsil_pipeline.resources.postgres import BsilPostgresResource


_DEFAULT_LOOKUP_PATH = (
    Path(__file__).resolve().parent.parent.parent / "data" / "bbox_lookup.sqlite"
)


def _load_postcodes_from_db(conn) -> set[str]:
    """Get distinct postcodes from LA extracts and Ofsted inspections."""
    postcodes = set()
    with conn.cursor() as cur:
        # LA extract postcodes
        cur.execute("""
            SELECT DISTINCT UPPER(TRIM(e.extracted_data->>'postcode'))
            FROM la.extract_results e
            WHERE e.extracted_data->>'postcode' IS NOT NULL
              AND e.extracted_data->>'postcode' != ''
        """)
        for (pc,) in cur.fetchall():
            if pc:
                postcodes.add(pc)

        # Ofsted inspections postcodes
        cur.execute("""
            SELECT DISTINCT UPPER(TRIM(provider_postcode))
            FROM ofsted.inspections
            WHERE provider_postcode IS NOT NULL
              AND provider_postcode != ''
        """)
        for (pc,) in cur.fetchall():
            if pc:
                postcodes.add(pc)

        # Ofsted scrape_results postcodes (real addresses for REDACTED providers)
        cur.execute("""
            SELECT DISTINCT UPPER(TRIM(provider_postcode))
            FROM ofsted.scrape_results
            WHERE provider_postcode IS NOT NULL
              AND provider_postcode != ''
        """)
        for (pc,) in cur.fetchall():
            if pc:
                postcodes.add(pc)

    return postcodes


def _outward_code(postcode: str) -> str | None:
    """Extract outward (district) code: 'SW1A 1AA' → 'SW1A'."""
    pc = postcode.strip().upper()
    if " " in pc:
        return pc.split()[0]
    if len(pc) >= 5:
        return pc[:-3].strip()
    return None


@asset(
    group_name="os",
    deps=[
        "bbox_lookup",
        "la_extract_results",
        "ofsted_inspections",
        "ofsted_scrape_results",
        "os_bounding_boxes_table",
        "os_la_name_lookup_table",
    ],
)
def os_bounding_boxes(
    context: AssetExecutionContext, bsil_postgres: BsilPostgresResource
):
    """Load bounding-box reference data from bbox_lookup.sqlite into Postgres.

    Depends on the bbox_lookup asset which generates the SQLite file from
    OS GeoPackage source data.

    Inserts per-postcode bboxes only for postcodes that appear in provider data.
    Loads ALL district and LA bboxes (~3,300 rows total).
    Idempotent: TRUNCATE + reload.
    """
    lookup_path = Path(os.environ.get("BBOX_LOOKUP_PATH", str(_DEFAULT_LOOKUP_PATH)))
    if not lookup_path.exists():
        context.log.error(
            f"bbox_lookup.sqlite not found at {lookup_path} — "
            "run the bbox_lookup asset first (make data/generate-bbox-lookup)"
        )
        return {"error": MetadataValue.text(f"Lookup file not found: {lookup_path}")}

    lookup = sqlite3.connect(str(lookup_path))

    with bsil_postgres.get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("TRUNCATE TABLE os.bounding_boxes")
            cur.execute("TRUNCATE TABLE os.la_name_lookup")
        conn.commit()

        # Determine which postcodes we need
        postcodes = _load_postcodes_from_db(conn)
        outward_codes = {_outward_code(pc) for pc in postcodes} - {None}
        context.log.info(
            f"Provider data has {len(postcodes)} distinct postcodes, "
            f"{len(outward_codes)} distinct outward codes"
        )

        counts = {
            "postcode": 0,
            "postcode_district": 0,
            "local_authority": 0,
            "county": 0,
        }

        # 1. Load matching postcode bboxes
        with conn.cursor() as cur:
            for pc in postcodes:
                row = lookup.execute(
                    "SELECT geo_name, bbox_north, bbox_south, bbox_east, bbox_west, postcode_count "
                    "FROM postcode_bbox WHERE geo_code = ?",
                    (pc,),
                ).fetchone()
                if row:
                    cur.execute(
                        """INSERT INTO os.bounding_boxes
                           (geo_type, geo_code, geo_name, bbox_north, bbox_south,
                            bbox_east, bbox_west, postcode_count)
                           VALUES ('postcode', %s, %s, %s, %s, %s, %s, %s)
                           ON CONFLICT DO NOTHING""",
                        (pc, *row),
                    )
                    counts["postcode"] += 1
        conn.commit()
        context.log.info(f"Loaded {counts['postcode']} postcode bboxes")

        # 2. Load ALL district bboxes (small table, useful for queries)
        with conn.cursor() as cur:
            district_rows = lookup.execute(
                "SELECT geo_code, geo_name, bbox_north, bbox_south, bbox_east, bbox_west, postcode_count "
                "FROM district_bbox"
            ).fetchall()
            for row in district_rows:
                cur.execute(
                    """INSERT INTO os.bounding_boxes
                       (geo_type, geo_code, geo_name, bbox_north, bbox_south,
                        bbox_east, bbox_west, postcode_count)
                       VALUES ('postcode_district', %s, %s, %s, %s, %s, %s, %s)
                       ON CONFLICT DO NOTHING""",
                    row,
                )
                counts["postcode_district"] += 1
        conn.commit()
        context.log.info(f"Loaded {counts['postcode_district']} district bboxes")

        # 3. Load ALL LA bboxes
        with conn.cursor() as cur:
            la_rows = lookup.execute(
                "SELECT geo_code, geo_name, bbox_north, bbox_south, bbox_east, bbox_west, postcode_count "
                "FROM la_bbox"
            ).fetchall()
            for row in la_rows:
                cur.execute(
                    """INSERT INTO os.bounding_boxes
                       (geo_type, geo_code, geo_name, bbox_north, bbox_south,
                        bbox_east, bbox_west, postcode_count)
                       VALUES ('local_authority', %s, %s, %s, %s, %s, %s, %s)
                       ON CONFLICT DO NOTHING""",
                    row,
                )
                counts["local_authority"] += 1
        conn.commit()
        context.log.info(f"Loaded {counts['local_authority']} LA bboxes")

        # 4. Load ALL county bboxes
        with conn.cursor() as cur:
            county_rows = lookup.execute(
                "SELECT geo_code, geo_name, bbox_north, bbox_south, bbox_east, bbox_west, postcode_count "
                "FROM county_bbox"
            ).fetchall()
            for row in county_rows:
                cur.execute(
                    """INSERT INTO os.bounding_boxes
                       (geo_type, geo_code, geo_name, bbox_north, bbox_south,
                        bbox_east, bbox_west, postcode_count)
                       VALUES ('county', %s, %s, %s, %s, %s, %s, %s)
                       ON CONFLICT DO NOTHING""",
                    row,
                )
                counts["county"] += 1
        conn.commit()
        context.log.info(f"Loaded {counts['county']} county bboxes")

        # 5. Build os.la_name_lookup from bounding_boxes geo_names
        #    Maps Ofsted local_authority names → (geo_type, geo_code)
        name_lookup_count = 0
        with conn.cursor() as cur:
            cur.execute("""
                SELECT geo_type, geo_code, geo_name
                FROM os.bounding_boxes
                WHERE geo_type IN ('local_authority', 'county')
                  AND geo_name IS NOT NULL
            """)
            bb_rows = cur.fetchall()

            for geo_type, geo_code, geo_name in bb_rows:
                # Generate name variants by stripping Boundary-Line suffixes
                variants = set()
                name = geo_name.strip()
                variants.add(name)

                # Strip common suffixes
                for suffix in [
                    " London Boro",
                    " District (B)",
                    " District",
                    " County",
                    " (B)",
                    " City",
                ]:
                    if name.endswith(suffix):
                        variants.add(name[: -len(suffix)].strip())

                # Strip leading prefixes
                for prefix in [
                    "City and County of the ",
                    "City of ",
                    "The City of ",
                    "County of ",
                    "County ",
                ]:
                    for v in list(variants):
                        if v.startswith(prefix):
                            variants.add(v[len(prefix) :].strip())

                # Generate additional variants
                extra = set()
                for v in variants:
                    # & ↔ and
                    if " and " in v:
                        extra.add(v.replace(" and ", " & "))
                    if " & " in v:
                        extra.add(v.replace(" & ", " and "))
                    # Hyphen ↔ space (Southend-on-Sea → Southend on Sea)
                    if "-" in v:
                        extra.add(v.replace("-", " "))
                    # St. ↔ St (St. Helens → St Helens)
                    if "St." in v:
                        extra.add(v.replace("St.", "St"))
                    if "St " in v and "St." not in v:
                        extra.add(v.replace("St ", "St. "))
                variants.update(extra)

                for v in variants:
                    if v:
                        cur.execute(
                            """INSERT INTO os.la_name_lookup (la_name, geo_type, geo_code)
                               VALUES (%s, %s, %s)
                               ON CONFLICT (la_name) DO NOTHING""",
                            (v, geo_type, geo_code),
                        )
                        name_lookup_count += 1

        conn.commit()
        context.log.info(f"Built la_name_lookup with {name_lookup_count} name variants")

    lookup.close()

    total = sum(counts.values())
    context.log.info(f"Bounding boxes load complete. Total: {total}, by type: {counts}")
    result = {k: MetadataValue.int(v) for k, v in counts.items()}
    result["la_name_lookup_variants"] = MetadataValue.int(name_lookup_count)
    return result
