import pandas as pd
import plotly.graph_objects as go
from dash import dcc

from layouts.field_bars_panel import PANEL_HEIGHT

# LA regions: neutral greys
LA_COLOR = "#d9d9d9"

# Palettes generated by evenly spacing hues around the HSL wheel.
# Institution types: saturated, medium lightness (S=0.65, L=0.45)
# Care types: saturated, lighter (S=0.55, L=0.60)
# This guarantees maximum distinction within each group and between groups.
INST_COLORS = {
    "nursery": "#bd2828",
    "childminder": "#bd8b28",
    "school_primary": "#8bbd28",
    "school_secondary": "#28bd28",
    "school_nursery": "#28bd8b",
    "school_special": "#288bbd",
    "school_independent": "#2828bd",
    "out_of_school_club": "#8b28bd",
    "unknown": "#969696",
    "(no institution type)": "#bdbdbd",
}

CARE_COLORS = {
    "private_nursery": "#d16060",
    "childminder": "#d1c160",
    "breakfast_club": "#80d160",
    "free_breakfast_club": "#60d1a1",
    "after_school_club": "#60a1d1",
    "holiday_club": "#8060d1",
    "school_based_nursery": "#d160c1",
    "(no care type)": "#bdbdbd",
}


def build_treemap(providers: pd.DataFrame, care_types: pd.DataFrame) -> go.Figure:
    """Build a treemap with hierarchy: LAD -> institution_type -> care_type.

    Uses go.Treemap directly so each hierarchy level gets its own color palette:
    - LA tiles: neutral grey
    - Institution type tiles: blue/teal
    - Care type tiles: warm orange/red/purple
    """
    cols = ["id", "lad25cd", "institution_type"]
    if "la_name" in providers.columns:
        cols.append("la_name")
    merged = care_types.merge(
        providers[cols].rename(columns={"id": "provider_id"}),
        on="provider_id",
        how="left",
    )

    if "la_name" in merged.columns:
        merged["lad_label"] = (
            merged["la_name"]
            .where(merged["la_name"].ne(""), other=merged["lad25cd"])
            .fillna("(no LA)")
        )
    else:
        merged["lad_label"] = merged["lad25cd"].fillna("(no LA)")
    merged["inst_label"] = merged["institution_type"].fillna("(no institution type)")
    merged["care_label"] = merged["care_type"].fillna("(no care type)")

    counts = (
        merged.groupby(["lad_label", "inst_label", "care_label"])
        .size()
        .reset_index(name="count")
    )

    if counts.empty:
        fig = go.Figure()
        fig.update_layout(height=PANEL_HEIGHT)
        return fig

    # Build arrays for go.Treemap: ids, labels, parents, values, colors
    ids = []
    labels = []
    parents = []
    values = []
    colors = []

    # Aggregate counts for intermediate levels
    inst_counts = (
        counts.groupby(["lad_label", "inst_label"])["count"].sum().reset_index()
    )
    la_counts = counts.groupby("lad_label")["count"].sum().reset_index()

    # Root level
    ids.append("England")
    labels.append("England")
    parents.append("")
    values.append(int(counts["count"].sum()))
    colors.append(LA_COLOR)

    # LA level
    for _, row in la_counts.iterrows():
        la = row["lad_label"]
        ids.append(la)
        labels.append(la)
        parents.append("England")
        values.append(row["count"])
        colors.append(LA_COLOR)

    # Institution level
    for _, row in inst_counts.iterrows():
        la = row["lad_label"]
        inst = row["inst_label"]
        tile_id = f"{la}/{inst}"
        ids.append(tile_id)
        labels.append(inst)
        parents.append(la)
        values.append(row["count"])
        colors.append(INST_COLORS.get(inst, "#636efa"))

    # Care type level (leaves)
    for _, row in counts.iterrows():
        la = row["lad_label"]
        inst = row["inst_label"]
        care = row["care_label"]
        tile_id = f"{la}/{inst}/{care}"
        ids.append(tile_id)
        labels.append(care)
        parents.append(f"{la}/{inst}")
        values.append(row["count"])
        colors.append(CARE_COLORS.get(care, "#ff7f0e"))

    fig = go.Figure(
        go.Treemap(
            ids=ids,
            labels=labels,
            parents=parents,
            values=values,
            marker=dict(colors=colors),
            branchvalues="total",
            textinfo="label+value",
            hovertemplate="%{label}<extra></extra>",
        )
    )
    fig.update_layout(
        height=PANEL_HEIGHT,
        margin={"l": 0, "r": 0, "t": 0, "b": 0},
    )
    return fig


treemap_panel = dcc.Graph(
    id="treemap-graph",
    figure=go.Figure(),
    config={"scrollZoom": False, "displayModeBar": False},
    style={"height": f"{PANEL_HEIGHT}px"},
)
