name: build-bsil-test

on:
  workflow_dispatch:
  workflow_call:
    # Ensure that when this workflow is called from another
    # the necessary secrets are passed down
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_STORAGE_CONNECTION_STRING:
        required: true

jobs:
  build-bsil-test:
    environment: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set environment config
        id: config
        run: |
          # TODO: Change this to be an actual variable rather than hard-coded
          echo "resource_group=s288d01rg-ukw-data" >> $GITHUB_OUTPUT
          echo "storage_account_name=cccepfdatastoredev" >> $GITHUB_OUTPUT
          echo "source_data=s288d01stc-ukw-sourcedata" >> $GITHUB_OUTPUT

      - name: Fetch exported data from blob storage
        run: |
          mkdir -p exported_data/app
          # I think that this is the equivalent to the AWS command
          # aws s3 sync s3://my-s3-bucket-url --delete

          az storage copy \
            --source-connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
            --source-container "${{ steps.config.outputs.source_data }}" \
            --source-blob "app/" \
            --destination exported_data/app/ \
            --recursive

          # az storage blob download-batch \
          #   -d exported_data/app/ \
          #   -s ${{ steps.config.outputs.source_data }} \
          #   --account-name "${{ steps.config.outputs.storage_account_name }}" \
          #   --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
          #   --pattern "app/*" \
          #   --overwrite true \
          #   --no-progress

      - name: Populate .docker-data for Docker build context
        run: |
          mkdir -p .docker-data/app
          cp -r ./exported_data/app/ .docker-data/app/

      - name: (TEMP) Print out current file structure
        run: |
          ls -la
          echo "\n\n"
          ls -la .docker-data
          echo "\n\n"
          ls -la .docker-data/app

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build bsil-test image
        run: |
          docker buildx build \
            --target test \
            --tag bsil-test \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --load \
            .