name: Main Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  # security scans ??? TBC

  # build-SIS-SPA:
  #   name: Build Spacial Index service + SPA
  #   permissions:
  #     contents: read
  #     id-token: write
  #   uses: ./.github/workflows/build.yml
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
  #     AZURE_SOURCE_DATA_CONTAINER_NAME: ${{ secrets.AZURE_SOURCE_DATA_CONTAINER_NAME }}

  build-infra:
    name: Build Infrastructure
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/build-infrastructure.yml
    with:
      infra-directory: infrastructure
      publish: true
  
  deploy-dev:
    name: Deploy Development
    permissions:
      id-token: write
      contents: read
      actions: read
    needs: [build-infra] 
      # build-SIS-SPA, 
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: Dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  
  # run tests ??? TBC